# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salesorder',
            table='salesorders',
        ),
    ]
